[package]
name = "server"
version = "0.1.0"
authors = ["Filippo Cucchetto <filippocucchetto@gmail.com>"]
build = "build.rs"

[dependencies]
docopt = "0.8.1"
error-chain = "0.11.0"
log = "0.3.8"
log4rs = "0.7.0"
native-tls = "0.1.4"
protobuf = "1.4.3"

[build-dependencies]
protoc-rust = "1.4.3"
